"""empty message

Revision ID: 06c08e636988
Revises: 9dbe052704cb
Create Date: 2017-03-30 17:22:13.992738

"""

# revision identifiers, used by Alembic.
revision = '06c08e636988'
down_revision = '9dbe052704cb'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('messages_offer_id_fkey', 'messages', type_='foreignkey')
    op.create_foreign_key(None, 'messages', 'offers', ['offer_id'], ['id'], ondelete='CASCADE')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.create_foreign_key('messages_offer_id_fkey', 'messages', 'offers', ['offer_id'], ['id'])
    ### end Alembic commands ###
