"""empty message

Revision ID: 26042dcc8fec
Revises: 06c08e636988
Create Date: 2017-04-01 21:14:56.987759

"""

# revision identifiers, used by Alembic.
revision = '26042dcc8fec'
down_revision = '06c08e636988'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('create_datetime', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'create_datetime')
    ### end Alembic commands ###
