"""empty message

Revision ID: 3d6d51b290e1
Revises: b3ea3d5fac07
Create Date: 2017-03-19 17:06:57.613493

"""

# revision identifiers, used by Alembic.
revision = '3d6d51b290e1'
down_revision = 'b3ea3d5fac07'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('first_name', sa.String(length=100), nullable=True))
    op.add_column('user', sa.Column('last_name', sa.String(length=100), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_name')
    op.drop_column('user', 'first_name')
    ### end Alembic commands ###
