"""empty message

Revision ID: 9dbe052704cb
Revises: 69c5ce6692a6
Create Date: 2017-03-30 17:16:23.896630

"""

# revision identifiers, used by Alembic.
revision = '9dbe052704cb'
down_revision = '69c5ce6692a6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('offers', sa.Column('executor_id', sa.Integer(), nullable=True))
    op.drop_constraint('offers_customer_id_fkey', 'offers', type_='foreignkey')
    op.create_foreign_key(None, 'offers', 'users', ['executor_id'], ['id'])
    op.drop_column('offers', 'customer_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('offers', sa.Column('customer_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'offers', type_='foreignkey')
    op.create_foreign_key('offers_customer_id_fkey', 'offers', 'users', ['customer_id'], ['id'])
    op.drop_column('offers', 'executor_id')
    ### end Alembic commands ###
